#
# XDP.INI
# For XDP Excalibur Edition
#

[System]

ScoreFiles='/xdptex/xdp.dps, /xdptex/softkey.dps, /xdptex/vms.dps, /xdptex/chat.dps, /xdptex/ntp.dps, /xdptex/pm.dps'
MessageFile='/xdptex/message.ini'
SoundDriverFile='/xdptex/manatee.drv'
SoundMLTFile='/xdptex/XDPsound.mlt'
SoundVolume=15
StaffRollFile='file:/dpwww/staff/roll.html'
ScreenSaverGDFile='/xdptex/SCRN1.GIF,/xdptex/SCRN2.GIF,/xdptex/SCRN3.GIF,/xdptex/SCRN4.GIF,/xdptex/SCRN5.GIF,/xdptex/SCRN6.GIF'
FontDir='/dpfont/'
SystemFont=S18RM04S.DAT
ZipCodeDBDir='/dpetc/'


#1=ON 0=OFF

URLChat=1
Ch@b Talk=1
100hdialog=0

#XDP for Reg Style color
BackgroundColor="#DFDFDF"
ScrollBackColor="#CCCCCC"
ScrollKnobColor="#ADADAE"
ScrollNoKnobBackColor="#7F7F7F"
ScrollButtonColor="#ADADAE"
StatusBarColor="#B9B9B9"
StatusBarFrameLT="#CCCCCC"
StatusBarFrameRB="#696969"
StatusBarTitleColor="#000000"
StatusBarTimeColor="#000000"
StatusBarConTimeColor="#005599"
StatusBarDisconTimeColor="#CC0000"
WndScrollBackColor="#CCCCCC"
WndScrollKnobColor="#ADADAE"
WndScrollNoKnobBackColor="#CCCCCC"
WndScrollButtonColor="#ADADAE"
WndCompoBackColor="#FFFFFF"
WndCompoFocusColor="#FF0000"
WndCompoNonFocusColor="#808080"
WndCompoCaretColor="#FF0000"
SofkeyTipsColor="#CCCCCC"
MsgBGColor="#CCCCCC"

[Dialog]

[MsgBox]

[Browser]

StartURL1='http://www.psilocybindreams.com'
StartPage='file:/dpwww/XDPdex.html'
NoProxyHosts='dricas.com,dricas.ne.jp,sega.co.jp,d-direct.ne.jp,port.ne.jp,segarally.com,shenmue.com,sega.com,sega-europe.com,webmoney.ne.jp,dreamcast.com,isao.net,isao.co.jp'
DefaultFunctionKey='http://|www.|.com|.net|.org|.html|x-avefront://---.dream/|file:/|'

DefaultBookmarkEntry='Google|http://www.google.com/,Shoryuken|http://www.shoryuken.com/,Psilocybin Dreams Web|http://www.psilocybindreams.com/,Online Consoles|http://www.onlineconsoles.com,Google|http://www.google.com,DCEmulation|http://www.dcemulation.com,XDP Browsers Group|http://groups.yahoo.com/group/xdpbrowsers,Dreamcast Browsers Group|http://www.dreamcastbrowsers.cjb.net/,Dreamcast Survivors Group|http://groups.yahoo.com/group/DreamCastSurvivorsGroup/,Booyaka|http://www.booyaka.com,PSO World|http://dynamic5.gamespy.com/~psoworld/,DC November|http://dreamcastnovember.tripod.com/,MSN eMessenger|http://www.e-messenger.net/index.php,Midi Datbase|http://www.mididb.com/'
DownloadLimitBytes=1572864


ConcealedURLPrefix='x-avefront:,javascript:,x-avefront://---.dream/proc/menu/,x-avefront://a--.avefront/navigation/,file:'
ProductPage='http://www.psilocybindreams.com'

#UploadIncludeFilter='PASSPORT.P**,PASSPORT.S**,PASSPORT.H**,PASSPORT.O**,PASSPORT.V**,PASSPORT.X**,DREAMKEY.S**,DREAMKEY.H**,DREAMKEY.X**,DREAMKEY.O**,DREAMKEY.P**,***********.ini,************.bin,*********.dps,**********.txt,'
#UploadExcludeFilter='PASSPORT.SY2'
#SerialNumberIncludeFilter=''PASSPORT.P**,PASSPORT.S**,PASSPORT.H**,PASSPORT.O**,PASSPORT.V**,PASSPORT.X**,DREAMKEY.S**,DREAMKEY.H**,DREAMKEY.X**,DREAMKEY.O**,DREAMKEY.P,*************.ini,************.bin,*********.dps,**********.txt,'
#SerialNumberExcludeFilter='PASSPORT.SY2'
#ProductPage='http://dreamcast.planetweb.com/'
AfterRegConnFailedPage='file:/dpwww/help/reconnect.htm'
AfterRegConnFailedPageUnknown='file:/dpwww/help/reconnect.htm'
AfterRegConnFailedPageModem='file:/dpwww/help/reconnect.htm'
AfterRegConnFailedPageBbA='file:/dpwww/help/reconnect.htm'
AfterRegConnFailedPageScif='file:/dpwww/help/reconnect.htm'

[Mailer]

XMailer='XDP Dream Passport'

#AppendIncludeFilter='PASSPORT.P**,PASSPORT.S**,PASSPORT.H**,PASSPORT.O**,PASSPORT.V**,PASSPORT.X**,DREAMKEY.S**,DREAMKEY.H**,DREAMKEY.X**,DREAMKEY.O**,DREAMKEY.P,*************.ini,************.bin,*********.dps,**********.txt,'
#AppendExcludeFilter='PASSPORT.SY2,**********.com,***********.scr,**********.bat'
#AcceptXMailer='XDP Dream Passport'

#XDP for Reg Style color
MailIconColor="#CCCCCC"
MailListTextColor="#000000"
MailListTextColorFocused="#004482"
MailListBackColor="#698CB5"
MailListColor="#4A7BB2"
MailListFocusColor="#FF0000"
MailListTitleColor="#FFFFFF"
MailListDelLineColor="#FF0000"
MailListDelBackColor="#808080"
MailListDelTitleColor="#C0C0C0"



[Launcher1]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='AR'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher2]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GS'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher3]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='JAPCVS'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher4]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='PF'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher5]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='ST'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher6]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='USA3S'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher7]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='USAMVC'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher8]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='JAP3S'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher9]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='JAPMVC'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher10]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='IKA'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher11]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='FANDISK'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher12]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='UTILS'
AppName='VMUTOOL.BIN'
AppOS=0
AppDA=3


[Launcher13]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='UTILS'
AppName='VMUUNSCR.BIN'
AppOS=0
AppDA=3

[Launcher14]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='UTILS'
AppName='DCLS.BIN'
AppOS=0
AppDA=3

[Launcher15]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='UTILS'
AppName='DCLIP.BIN'
AppOS=0
AppDA=3

[Launcher16]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='UTILS'
AppName='DCLIP10.BIN'
AppOS=0
AppDA=3

[Launcher17]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='UTILS'
AppName='DCLIP192.BIN'
AppOS=0
AppDA=3

[Launcher18]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='TST'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher19]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='TPF'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher21]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='UTILS'
AppName='NOIZ2.BIN'
AppOS=0
AppDA=3

[Launcher22]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='UTILS'
AppName='NEOCDUNS.BIN'
AppOS=0
AppDA=3

[Launcher23]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME23'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher24]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME24'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher26]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME26'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher27]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME27'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher28]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME28'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher29]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME29'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher20]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME20'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher25]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME25'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher34]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME34'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher36]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME36'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher37]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME37'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher38]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME38'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher39]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME39'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher30]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME30'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher42]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME42'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher46]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME46'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher47]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME47'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher48]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME48'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher45]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME45'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher49]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME49'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher40]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME40'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher41]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME41'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher52]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME52'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher56]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME56'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher57]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME57'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher58]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME58'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher59]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME59'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher50]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME50'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher62]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME62'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher64]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME64'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3



[Launcher67]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME67'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher68]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME68'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher69]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME69'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher60]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME60'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher71]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME71'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher72]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME72'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher73]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME73'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher74]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME74'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher75]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME75'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher76]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='CVS1J'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher77]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME77'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher78]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME78'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher79]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME79'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher81]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME81'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher82]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME82'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher83]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME83'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher84]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME84'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher86]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME86'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher87]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME87'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3




[Launcher89]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME89'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3


[Launcher80]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME80'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher90]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME92'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher94]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME94'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher96]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME96'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher97]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME97'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher99]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME99'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher100]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME100'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher102]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME102'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher104]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME104'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher106]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME106'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher108]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME108'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Launcher109]

AppUrl='file:/dpwww/xdpdex.html'
AppDir='GAME109'
AppName='1ST_READ.BIN'
AppOS=0
AppDA=3

[Game_ID]

XGame_ID='610-7819'
XGame_Ver='V1.999'
