#
# dp2.ini
#
# [section]
# # comment
# name1=value1
# name2="Welcome to 'Dreamcast!'"
# name3='Welcome to "Dreamcast!"'
#
# * [ ’¤Ï’É¬’¤º’¹Ô’Æ¬’¤Ë’ÃÖ’¤¯
# * name’¤Ï’É¬’¤º’¹Ô’Æ¬’¤Ë’ÃÖ’¤¯
# * =’¤Î’º¸’±¦’¤Ë’¥¹’¥Ú’¡¼’¥¹’¤ò’ÃÖ’¤«’¤Ê’¤¤
# * section, name’¤È’¤â’¡¤’Âç’Ê¸’»ú’¾®’Ê¸’»ú’¤Î’¶è’ÊÌ’¤Ï’¤Ê’¤¤
# * ’¥¹’¥Ú’¡¼’¥¹’¤ò’´Þ’¤à’Ê¸’»ú’Îó’¤ò’»Ø’Äê’¤¹’¤ë’¾ì’¹ç’¤Ï "" or '' ’¤Ç’¤¯’¤¯’¤ë
#


[System]

ScoreFiles='/dpetc/dp2.dps, /dpetc/softkey.dps, /dpetc/vms.dps'
MessageFile='/dpetc/message.ini'
SoundDriverFile='/dpetc/manatee.drv'
SoundMLTFile='/dpetc/DP2sound.mlt'
SoundVoiceDir='/dpetc/'
SoundVoiceName='voice.afs'
#StaffRollFile='/dpwww/end.sfd'
#ScreenSaverGDFile='/dpss/001.gif,/dpss/002.gif,/dpss/003.gif,/dpss/004.gif,/dpss/005.gif,/dpss/006.gif,/dpss/007.gif,/dpss/008.gif,/dpss/009.gif,/dpss/010.gif,/dpss/011.gif,/dpss/012.gif,/dpss/013.gif,/dpss/014.gif,/dpss/015.gif,/dpss/016.gif,/dpss/017.gif,/dpss/018.gif,/dpss/019.gif,/dpss/020.gif,/dpss/021.gif,/dpss/022.gif,/dpss/023.gif,/dpss/024.gif,/dpss/025.gif,/dpss/026.gif,/dpss/027.gif'
#ScreenSaverGDFile='/dpss/l_adv2logo.gif,/dpss/l_amy.gif,/dpss/l_chao2.gif,/dpss/l_eggman.gif,/dpss/l_knuckles.gif,/dpss/l_nchao.gif,/dpss/l_rouge.gif,/dpss/l_shadow.gif,/dpss/l_sonic.gif,/dpss/l_tails.gif'
ScreenSaverGDFile='/dpss/036.gif'
FontDir='/dpfont/'
SystemFont=s20rm04s.dat
ZipCodeDBDir='/dpetc/'


[Dialog]


[MsgBox]


[Browser]

AuxUserAgent="SonicKey2"
ConcealedURLPrefix='x-avefront:, file:, http://www.sega.com'
ProductPage='file:/dpwww/index.html'

#{ 04/26/2001 SAITO
#StartURL10='http://sonic.dricas.ne.jp/sonicadv/bbs/c/chao/index.shtml'
StartURL10='http://sonic2.dricas.ne.jp/chao/bbstop'
#} 04/26/2001 SAITO
StartPage='file:/dpwww/index.html'
NoProxyHosts='dream-key.com,portal.dream-key.com,email.dream-key.com,chat.dream-key.com,shop.dream-key.com,registration.dream-key.com,authentication.dream-key.com'
ConcealedURLPrefix='x-avefront:,file:'
DefaultFunctionKey='www.|.co|.ne|.ac|.or|.jp/|.com/|.uk/|/~|.html|.htm'
DefaultBookmarkEntry='SEGA OF Japan|http://www.sega.co.jp/home_e.html,SEGA OF America|http://www.sega.com/,SEGA OF Europe|http://www.sega-europe.com/,ACCESS Co. Ltd.|http://www.access.co.jp/DC/english/'
DownloadLimitBytes=1572864

#UploadIncludeFilter='DREAMKEY.P**,DREAMKEY.S**'
#UploadExcludeFilter='DREAMKEY.SY2'
#SerialNumberIncludeFilter='DREAMKEY.P**,DREAMKEY.S**'
#SerialNumberExcludeFilter='DREAMKEY.SY2'
#ProductPage='http://www.sonic.com'


[Mailer]

XMailer='DreamKey version 1 SEGA/SONICADVENTURE2'
#AppendIncludeFilter='DREAMKEY.P**,DREAMKEY.S**'
#AppendExcludeFilter='DREAMKEY.SY2'
#AcceptXMailer='DreamKey version 1'


[Help]
AfterRegConnFailed.English=file:/dpwww/warning/LOCAL_AUTH01_UK.htm
AfterRegConnFailed.German=file:/dpwww/warning/LOCAL_AUTH01_UK.htm
AfterRegConnFailed.French=file:/dpwww/warning/LOCAL_AUTH01_UK.htm
AfterRegConnFailed.Spanish=file:/dpwww/warning/LOCAL_AUTH01_UK.htm
AfterRegConnFailed.Italian=file:/dpwww/warning/LOCAL_AUTH01_UK.htm


[LocationInfo]

TimeZoneDiff=-8
PulseOrTone=Tone
StartPage='file:/dpwww/index.html'